### ISSUE TITLE
hevc_rkmpp_decoder

### ISSUE THREAD

**Issue by great9** [hbiyik/FFmpeg#45]
I am getting "[hevc_rkmpp_decoder @ 0x...] Can not get out frame"
Is this an mpp bug or the exp_refactor_all branch?

**Comment by hbiyik** [comment]
This is only a case with exp_refactor_all branch. It is trying to manage decoder and rga conversion at the same time with limited memory range (4GB due to rga limitation).

https://github.com/hbiyik/FFmpeg/blob/65d4cf4bd74904dcbcd935685d2160da83f8f72d/libavcodec/rkmppdec.c#L396C1-L397C1 you can increase the preallocated buffer counts here, but take note increasing those will cause OOM for 8k videos.

All of those are handled in a better way in https://github.com/nyanmisaka/ffmpeg-rockchip/ therefore i dont plan to improve this fork any more, you can try numbers if you want.

**Comment by great9** [comment]
I'm now on ffmpeg-rockchip repo
